name: Firebase deployment
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@develop
        with:
          args: deploy --only hosting:nutriaescom
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}